#!/usr/bin/env bash
# ghostty-theme.sh — regenerate ~/.config/ghostty/colors.conf from the
# live pywal palette and hot-reload Ghostty.
#
# Ghostty reads its own config syntax and can't @import the GTK-CSS wal
# files the rest of the rice shares (AGENTS.md palette contract). Both
# palette producers converge on ~/.cache/wal/colors.sh, so ONE hook
# covers them:
#   wallpaper mode — hyprland.conf's exec-once runs this right after
#                    `wal -i`
#   preset mode    — switch-theme.sh runs this after copying a preset
#
# The generated file is included by ~/.config/ghostty/config via
# `config-file = ?colors.conf`. It only sets background/foreground/
# palette 0-15 — the baked Mocha block in config stays the fallback and
# selection-*/cursor-color keep reading from it.

set -euo pipefail

if [[ $EUID -eq 0 ]]; then
    echo "Run as normal user, not root."
    exit 1
fi

WAL="$HOME/.cache/wal/colors.sh"
OUT="$HOME/.config/ghostty/colors.conf"

if [[ ! -f "$WAL" ]]; then
    # No palette yet (never ran wal / switch-theme) — the baked Mocha
    # fallback in ghostty's config stands. Not an error.
    exit 0
fi

echo "==> [1/2] Writing $OUT from $WAL"
# colors.sh defines background/foreground/color0..color15 as '#rrggbb'
# strings; Ghostty accepts '#rrggbb' or bare — we emit bare. (Verified
# against ghostty's option reference, not assumed.)
# shellcheck disable=SC1090
source "$WAL"
mkdir -p "$HOME/.config/ghostty"
{
    echo "# Generated by ghostty-theme.sh from ~/.cache/wal/colors.sh — do not edit."
    echo "background = ${background#\#}"
    echo "foreground = ${foreground#\#}"
    for i in $(seq 0 15); do
        name="color$i"
        echo "palette = $i=${!name#\#}"
    done
} > "$OUT"

echo "==> [2/2] Reloading Ghostty (only if it's already running)"
if command -v ghostty >/dev/null 2>&1 && pgrep -x ghostty >/dev/null 2>&1; then
    ghostty +reload-config >/dev/null 2>&1 || true
    echo "    ghostty reloaded."
else
    echo "    ghostty not running (or not installed yet) — nothing to reload."
fi
