;; =============================================================================
;; init.el — Emacs config for the linux-rice.
;;
;; Single-file, minimal-by-design, NO package manager / no third-party
;; packages — same philosophy as config/nvim/init.lua. Pulls colors from
;; pywal16's cache (~/.cache/wal/colors.el, rendered from the custom user
;; template at config/wal/templates/colors.el) so Emacs matches the rest
;; of the rice; falls back to baked Catppuccin Mocha when pywal hasn't
;; run. Emacs is an OPT-IN install (00-base.sh prompts) — Zed and nvim
;; remain the default editors.
;;
;; NOTE: Emacs reads this file from ~/.config/emacs/init.el only if
;; ~/.emacs.d does not exist (XDG rules). If you have an old ~/.emacs.d,
;; this config is ignored — move it aside.
;; =============================================================================

;; ---- Quality of life --------------------------------------------------------
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
(setq inhibit-startup-screen t
      initial-scratch-message nil
      ring-bell-function 'ignore
      make-backup-files nil
      auto-save-default nil
      create-lockfiles nil)

(setq-default indent-tabs-mode nil
              tab-width 4)

(electric-pair-mode 1)
(show-paren-mode 1)
(global-auto-revert-mode 1)        ; like nvim's autoread/checktime
(setq global-auto-revert-non-file-buffers t)

(column-number-mode 1)
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
(global-hl-line-mode 1)

(setq scroll-margin 4)
(when (fboundp 'pixel-scroll-precision-mode)
  (pixel-scroll-precision-mode 1))

(setq search-highlight t
      case-fold-search t)

;; Clipboard via the system (wl-clipboard under Wayland)
(setq select-enable-clipboard t)

;; ---- Palette: pywal16 first, Catppuccin Mocha fallback ---------------------
;; Same contract as nvim: ~/.cache/wal/colors.el is generated by `wal -i`
;; from config/wal/templates/colors.el and defines wal-* hex strings.
;; No theme package involved.

(let ((wal-el (expand-file-name "~/.cache/wal/colors.el"))
      (bg "#1e1e2e") (bg-alt "#181825") (fg "#cdd6f4")
      (red "#f38ba8") (green "#a6e3a1") (yellow "#f9e2af")
      (blue "#89b4fa") (magenta "#f5c2e7") (cyan "#94e2d5")
      (comment "#6c7086") (selection "#585b70") (border "#313244"))
  (when (file-readable-p wal-el)
    (load-file wal-el)
    (setq bg wal-background
          bg-alt wal-color0
          fg wal-foreground
          red wal-color1
          green wal-color2
          yellow wal-color3
          blue wal-color4
          magenta wal-color5
          cyan wal-color6
          comment wal-color8
          selection wal-color8
          border wal-color0))
  (custom-set-faces
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:background ,bg))))
   `(line-number ((t (:foreground ,comment :background ,bg))))
   `(line-number-current-line ((t (:foreground ,yellow :background ,bg-alt :weight bold))))
   `(region ((t (:background ,selection))))
   `(highlight ((t (:background ,selection))))
   `(isearch ((t (:background ,yellow :foreground ,bg))))
   `(lazy-highlight ((t (:background ,blue :foreground ,bg))))
   `(hl-line ((t (:background ,bg-alt))))
   `(mode-line ((t (:background ,bg-alt :foreground ,fg :box (:color ,border)))))
   `(mode-line-inactive ((t (:background ,bg-alt :foreground ,comment :box (:color ,border)))))
   `(vertical-border ((t (:foreground ,border))))
   `(font-lock-comment-face ((t (:foreground ,comment :italic t))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-keyword-face ((t (:foreground ,magenta))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight bold))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-constant-face ((t (:foreground ,yellow))))
   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-preprocessor-face ((t (:foreground ,blue))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(show-paren-match ((t (:background ,selection))))))

;; ---- Keymaps (C-c prefix; SPC-as-leader would break typing in Emacs) -------
;; Mirrors the nvim conveniences where they translate.
(global-set-key (kbd "C-c w") #'save-buffer)          ; nvim <leader>w
(global-set-key (kbd "C-c q") #'kill-current-buffer)  ; nvim <leader>q
(global-set-key (kbd "C-c e") #'dired-jump)           ; nvim <leader>e
(global-set-key (kbd "C-c b") #'switch-to-buffer)     ; buffer switch
(global-set-key (kbd "C-c n") #'display-line-numbers-mode) ; toggle numbers
