;; =============================================================================
;; init.el — Emacs config for the linux-rice.
;;
;; Single-file, minimal-by-design, NO package manager / no third-party
;; packages — same philosophy as config/nvim/init.lua. Pulls colors from
;; pywal16's cache (~/.cache/wal/colors.el, rendered from the custom user
;; template at config/wal/templates/colors.el) so Emacs matches the rest
;; of the rice; falls back to baked Catppuccin Mocha when pywal hasn't
;; run. Emacs is an OPT-IN install (00-base.sh's [8/8] block prompts for
;; it, and installs emacs-wayland — the PGTK/native-Wayland build) —
;; Zed and nvim remain the default editors.
;;
;; LSP: use the built-in eglot (`M-x eglot` in a project buffer). It's
;; part of Emacs core since 29, so no package manager is needed here —
;; the servers themselves (pyright, clangd, rust-analyzer, gopls, ...)
;; are installed by 00-base.sh's [4/8] block.
;;
;; NOTE: Emacs reads this file from ~/.config/emacs/init.el only if
;; ~/.emacs.d does not exist (XDG rules). If you have an old ~/.emacs.d,
;; this config is ignored — move it aside.
;; =============================================================================

;; ---- Quality of life --------------------------------------------------------
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
(setq inhibit-startup-screen t
      initial-scratch-message nil
      ring-bell-function 'ignore
      make-backup-files nil
      auto-save-default nil
      create-lockfiles nil)

(setq-default indent-tabs-mode nil
              tab-width 4)

(electric-pair-mode 1)
(show-paren-mode 1)
(global-auto-revert-mode 1)        ; like nvim's autoread/checktime
(setq global-auto-revert-non-file-buffers t)

(column-number-mode 1)
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
(global-hl-line-mode 1)

(setq scroll-margin 4)
(when (fboundp 'pixel-scroll-precision-mode)
  (pixel-scroll-precision-mode 1))

(setq search-highlight t
      case-fold-search t)

;; Clipboard via the system (wl-clipboard under Wayland)
(setq select-enable-clipboard t)

;; ---- Palette: pywal16 first, Catppuccin Mocha fallback ---------------------
;; Same contract as nvim: ~/.cache/wal/colors.el is generated by `wal -i`
;; from config/wal/templates/colors.el and defines wal-* hex strings.
;; No theme package involved.

(let ((wal-el (expand-file-name "~/.cache/wal/colors.el"))
      (bg "#1e1e2e") (bg-alt "#181825") (fg "#cdd6f4")
      (red "#f38ba8") (green "#a6e3a1") (yellow "#f9e2af")
      (blue "#89b4fa") (magenta "#f5c2e7") (cyan "#94e2d5")
      (comment "#6c7086") (selection "#585b70") (border "#313244"))
  (when (file-readable-p wal-el)
    (load-file wal-el)
    (setq bg wal-background
          bg-alt wal-color0
          fg wal-foreground
          red wal-color1
          green wal-color2
          yellow wal-color3
          blue wal-color4
          magenta wal-color5
          cyan wal-color6
          comment wal-color8
          selection wal-color8
          border wal-color0))
  (custom-set-faces
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:background ,bg))))
   `(line-number ((t (:foreground ,comment :background ,bg))))
   `(line-number-current-line ((t (:foreground ,yellow :background ,bg-alt :weight bold))))
   `(region ((t (:background ,selection))))
   `(highlight ((t (:background ,selection))))
   `(isearch ((t (:background ,yellow :foreground ,bg))))
   `(lazy-highlight ((t (:background ,blue :foreground ,bg))))
   `(hl-line ((t (:background ,bg-alt))))
   `(mode-line ((t (:background ,bg-alt :foreground ,fg :box (:color ,border)))))
   `(mode-line-inactive ((t (:background ,bg-alt :foreground ,comment :box (:color ,border)))))
   `(vertical-border ((t (:foreground ,border))))
   `(font-lock-comment-face ((t (:foreground ,comment :italic t))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-keyword-face ((t (:foreground ,magenta))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight bold))))
   `(font-lock-variable-name-face ((t (:foreground ,blue))))
   `(font-lock-type-face ((t (:foreground ,cyan))))
   `(font-lock-constant-face ((t (:foreground ,yellow))))
   `(font-lock-builtin-face ((t (:foreground ,blue))))
   `(font-lock-preprocessor-face ((t (:foreground ,blue))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,blue :weight bold))))
   `(show-paren-match ((t (:background ,selection))))))

;; ---- Keymaps (C-c prefix; SPC-as-leader would break typing in Emacs) -------
;; Mirrors the nvim conveniences where they translate. Using C-c as a
;; prefix is Emacs-native convention (it's reserved for user bindings, so
;; we never clobber a built-in key) — deliberately NOT a copy of nvim's
;; SPC-leader scheme, which would shadow every self-insert command here.
(global-set-key (kbd "C-c w") #'save-buffer)          ; nvim <leader>w
(global-set-key (kbd "C-c q") #'kill-current-buffer)  ; nvim <leader>q
(global-set-key (kbd "C-c e") #'dired-jump)           ; nvim <leader>e
(global-set-key (kbd "C-c b") #'switch-to-buffer)     ; buffer switch
(global-set-key (kbd "C-c n") #'display-line-numbers-mode) ; toggle numbers

;; ---- fats-mode / supermode (F2 toggles) --------------------------------------
;; Same F2 contract as config/nvim/init.lua:
;;   supermode = this file's DEFAULT. A hand-rolled vim-ish motion layer:
;;               h j k l move point, w b word motion, `i` drops into the
;;               insert phase (ordinary self-inserting Emacs); <escape> or
;;               C-g (which also quits) from the insert phase goes back to
;;               motion. Deliberately minimal — no operators, registers,
;;               text objects, or visual state; that goalpost is what
;;               evil-mode is for, and this file ships no packages.
;;   fats-mode = stock Emacs editing except C-s saves (was
;;               isearch-forward), C-z undoes (was suspend-frame) and
;;               C-a selects all (was move-beginning-of-line).
;; F2 flips between them. Stock Emacs is neither mode; we default to
;; supermode at startup to mirror nvim. The mode-line lighter
;; (SUPER / FATS / super/insert) shows which mode is live.

(defun supermode--motion-command (command char)
  "Build a supermode motion key: run COMMAND, but self-insert CHAR in
the minibuffer so prompts (M-x, isearch, ...) stay typable while the
motion phase is on. The lambda SPLICES its arguments instead of closing
over them: this file runs under Emacs' default dynamic binding (no
lexical-binding cookie), where a closure's variables are void by the
time the key fires."
  `(lambda (arg)
     (interactive "p")
     (if (minibufferp)
         (self-insert-command arg ,char)
       (funcall #',command arg))))

(defvar supermode-motion-map (make-sparse-keymap)
  "Keymap for supermode's motion phase.")
(defvar supermode-insert-map (make-sparse-keymap)
  "Keymap for supermode's insert phase (plain self-inserting Emacs).")
(defvar fats-mode-map (make-sparse-keymap)
  "Keymap for fats-mode's C-s/C-z/C-a remaps.")

(define-minor-mode supermode-motion-mode
  "Motion phase of supermode (see header comment). Part of the F2 toggle."
  :global t
  :lighter " SUPER"
  :keymap supermode-motion-map)

(define-minor-mode supermode-insert-mode
  "Insert phase of supermode: ordinary Emacs typing, ESC/C-g back to motion."
  :global t
  :lighter " super/insert"
  :keymap supermode-insert-map)

(define-minor-mode fats-mode
  "C-s saves, C-z undoes, C-a selects all. Off in supermode; F2 toggles."
  :global t
  :lighter " FATS"
  :keymap fats-mode-map)

(defun supermode-enter-motion ()
  "Switch supermode to its motion phase."
  (interactive)
  (supermode-insert-mode -1)
  (supermode-motion-mode 1))

(defun supermode-enter-insert ()
  "Switch supermode to its insert phase (vim's `i`)."
  (interactive)
  (supermode-motion-mode 0)
  (supermode-insert-mode 1))

(defun supermode-motion-quit ()
  "C-g in the insert phase: quit whatever was happening, then motion."
  (interactive)
  (supermode-enter-motion)
  (keyboard-quit))

(define-key supermode-motion-map (kbd "h") (supermode--motion-command #'backward-char ?h))
(define-key supermode-motion-map (kbd "j") (supermode--motion-command #'next-line ?j))
(define-key supermode-motion-map (kbd "k") (supermode--motion-command #'previous-line ?k))
(define-key supermode-motion-map (kbd "l") (supermode--motion-command #'forward-char ?l))
(define-key supermode-motion-map (kbd "w") (supermode--motion-command #'forward-word ?w))
(define-key supermode-motion-map (kbd "b") (supermode--motion-command #'backward-word ?b))
(define-key supermode-motion-map (kbd "i") #'supermode-enter-insert)

(define-key supermode-insert-map (kbd "<escape>") #'supermode-enter-motion)
(define-key supermode-insert-map (kbd "C-g") #'supermode-motion-quit)

(define-key fats-mode-map (kbd "C-s") #'save-buffer)
(define-key fats-mode-map (kbd "C-z") #'undo)
(define-key fats-mode-map (kbd "C-a") #'mark-whole-buffer)

(defun rice-toggle-edit-mode ()
  "F2: flip between fats-mode and supermode (nvim uses the same key)."
  (interactive)
  (if fats-mode
      (progn
        (fats-mode -1)
        (supermode-enter-motion)
        (message "supermode: hjkl/wb motion, i = insert, F2 = fats-mode"))
    (supermode-motion-mode -1)
    (supermode-insert-mode -1)
    (fats-mode 1)
    (message "fats-mode: C-s save, C-z undo, C-a select-all; F2 = supermode")))
(global-set-key (kbd "<f2>") #'rice-toggle-edit-mode)

;; Startup default: supermode (motion phase), matching nvim's default.
(supermode-motion-mode 1)
